version: '3.8'

services:
  crm-qarvon:
    image: crm-qarvon:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-qarvon
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    extra_hosts:
      # Troque pelo SEU dom√≠nio exato do endpoint do Logto
      - "crm-logto.vodct5.easypanel.host:host-gateway"
    ports:
      - "3000:3000"
    # To connect to supabase, logto, and listmonk, it's best to join them on the same network
    networks:
      - app-net

# Assume a shared network exists if Supabase, Logto, etc are already deployed with Docker.
# Change the network name to whatever your existing network is named.
networks:
  app-net:
    external: true
    name: 'supabase-network' # Change this if your network is named differently
